app:
  name: example
  debug: true
log:
  level: "debug"
  format: "json"
rest:
  port: 8985
  cors:
    default: true
database:
  driver: postgres
  postgres:
    dns: "postgres://root:root@localhost:5432/liquor?sslmode=disable"
  # origin:
  #   - "*"
  # methods:
  #   - "GET"
  #   - "POST"
  #   - "PUT"
  #   - "DELETE"
  #   - "OPTIONS"
  # headers:
  #   - "Origin"
  #   - "Authorization"
  #   - "Content-Type"
  # credentials: true